sudo: false
language: python
install: pip install tox
matrix:
  include:
  - python: "2.7"
    env: TOX_ENV=py27
  - python: "3.7"
    env: TOX_ENV=py37
  - python: "3.7"
    env: TOX_ENV=pycodestyle
  #- python: "3.7"
  # env: TOX_ENV=pidiff
  - python: "3.7"
    env: TOX_ENV=cov-travis DEPLOY=1
  - python: "3.7"
    env: TOX_ENV=docs
script: tox -e $TOX_ENV
after_success:
- test $TOX_ENV = docs && scripts/push-docs

deploy:
  # Adding a new tag automatically releases to PyPI.
  provider: pypi
  user: __token__
  password:
    secure: yq8w8YQi+wnVHhxOcPVLkxjVnpeskXuTVPn568C5JZ2VNZHhflrM/uAEF1jk+FiKMLxsX1Ux1InnNNN8kXXvuyCT2AcTCnAjDg2YgNADvnCJJXSv+LxvnyRa3YCj/GoXZ4S5kXxaQGKxHxCgQNS2TctFl3+Mo6cr1ICoBKSSuLMUivTHxpUDfuyb/0yFke0X1x74Y7DkOW9in8Anu3qbDC3XZ/f59lbnqtWxBCjzXosTRr/h48yci1O9/NV78eu4Lm7KKNPGSgLRE3retzPuOjRgXgJ8xjvqyCvdNgh9qInvwN4XkQQwyaTO0whX/Ru21Xd/vhlDn40BeY7zLFm0+oimQ7ctyAyGGg//qIc1KmftE36fmJrJdEQrGh+97HYMWGSr9SfR7VA0dnvyEPhbupszEaVDS7dL+GfUJ0KrU84YaPvFki51Yxt+lhYg9HwhNcZQu8m74PQ0SaWpuAe+EYEObY2TcNOlGNGFqIBO4Fc6GVasoKNvXYgjXg2zlVEW6eejqHJq0o2j8I5rHRfmoEnP8WGFvDN+cZWHVB3tpfs6HnGv1IfO+UhO00yd+v5F2lKtPBPMrUSEUGxI7FylQYeylUPFVFSHldky0eV9Z4x7kOd4rhogHCnB/98ucNb/n+v9NWvnzDvvVIAERfeyX3qG2VpbB323rKQpQKQbN8M=
  on:
    tags: true
    # Only one of the environments in the matrix should have
    # deployments enabled. It's mostly arbitrary which one,
    # but best to select some Python 3.x so up-to-date tools
    # are used during release.
    condition: $DEPLOY = 1
  skip_existing: true

