name: Tox tests

on: [push, pull_request]

jobs:
  py310:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py310 -vv
  pycodestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e pycodestyle -vv
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e docs -vv
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e mypy -vv
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py310
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          verbose: true
  bandit-exitzero:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install RPM
        run: sudo apt-get install -y rpm libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py3-bandit-exitzero
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install RPM
        run: sudo apt-get install -y rpm libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py3-bandit
